apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjMkZ1ZEdWamFHNXBjWFZsZFdVNloyaHdYMEU0UldGeVF6SXhTazlzWWxsS01EZHpSRGN3Yms0eE9GaGpZbVpIVnpONFRraG5WZz09In19fQ==
type: kubernetes.io/dockerconfigjson
